SELECT DISTINCT(CITY)
FROM STATION
WHERE CITY NOT IN 
(SELECT DISTINCT(CITY)
 FROM STATION
 WHERE
    CITY Like 'A%' OR
    CITY Like 'E%' OR
    CITY Like 'I%' OR
    CITY Like 'O%' OR
    CITY Like 'U%');