SELECT WANDS.ID,
    WANDS_PROPERTY.AGE,
    WANDS.COINS_NEEDED,
    WANDS.POWER
FROM WANDS
INNER JOIN WANDS_PROPERTY ON WANDS_PROPERTY.CODE = WANDS.CODE
WHERE WANDS_PROPERTY.IS_EVIL = 0 AND WANDS.COINS_NEEDED = 
(SELECT MIN(W.COINS_NEEDED)
 FROM WANDS W
 INNER JOIN WANDS_PROPERTY WP ON WP.CODE = W.CODE
 WHERE WANDS.POWER = W.POWER AND WP.AGE = WANDS_PROPERTY.AGE)
ORDER BY WANDS.POWER DESC, WANDS_PROPERTY.AGE DESC;