SELECT IF(GRADES.GRADE >= 8,STUDENTS.NAME, 'NULL'),
        GRADES.GRADE, STUDENTS.MARKS
FROM STUDENTS, GRADES
WHERE STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND MAX_MARK
ORDER BY GRADES.GRADE DESC, STUDENTS.NAME;