SELECT HACKERS.HACKER_ID, HACKERS.NAME
FROM HACKERS
INNER JOIN SUBMISSIONS ON SUBMISSIONS.HACKER_ID = HACKERS.HACKER_ID
INNER JOIN CHALLENGES ON CHALLENGES.CHALLENGE_ID = SUBMISSIONS.CHALLENGE_ID
INNER JOIN DIFFICULTY ON DIFFICULTY.DIFFICULTY_LEVEL = CHALLENGES.DIFFICULTY_LEVEL
WHERE SUBMISSIONS.SCORE = DIFFICULTY.SCORE AND  CHALLENGES.DIFFICULTY_LEVEL = DIFFICULTY.DIFFICULTY_LEVEL
GROUP BY HACKERS.HACKER_ID, HACKERS.NAME
HAVING COUNT(SUBMISSIONS.HACKER_ID) > 1
ORDER BY  COUNT( SUBMISSIONS.HACKER_ID) DESC, SUBMISSIONS.HACKER_ID;
